version: '2'

services:
  django:
    build:
      context: .
      dockerfile: ./compose/django/Dockerfile-dev
    command: /gunicorn.sh
    env_file: dev.env
    volumes:
      - .:/app
    ports:
      - "5000:5000"

  celeryworker:
    build:
      context: .
      dockerfile: ./compose/django/Dockerfile-dev
    env_file: dev.env
    volumes:
      - .:/app
    command: celery -A noticeapp.taskapp worker -l INFO

  celerybeat:
    build:
      context: .
      dockerfile: ./compose/django/Dockerfile-dev
    env_file: dev.env
    volumes:
      - .:/app
    command: celery -A noticeapp.taskapp beat -l INFO

